# Generated by Django 2.0.6 on 2018-06-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180609_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='title',
        ),
    ]
