# Generated by Django 2.0.6 on 2018-06-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
