# Generated by Django 2.0.6 on 2018-06-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180612_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='intro',
        ),
    ]
