# Generated by Django 2.0.6 on 2018-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.AddField(
            model_name='post',
            name='themes',
            field=models.ManyToManyField(choices=[('UND', 'Undefined'), ('TEC', 'Technology'), ('INT', 'Internet'), ('SCI', 'Science'), ('MOV', 'Movies'), ('TV', 'TV'), ('SPO', 'Sports'), ('GAM', 'Games')], default='UND', related_name='_post_themes_+', to='posts.Post'),
        ),
    ]
