# Generated by Django 2.0.6 on 2018-06-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180615_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='themes',
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('UND', 'Undefined'), ('TEC', 'Technology'), ('INT', 'Internet'), ('SCI', 'Science'), ('MOV', 'Movies'), ('TV', 'TV'), ('SPO', 'Sports'), ('GAM', 'Games')], default='UND', max_length=3),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
