# Generated by Django 2.0.6 on 2018-06-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
        ('posts', '0016_auto_20180615_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.AddField(
            model_name='post',
            name='themes',
            field=models.ManyToManyField(to='themes.Theme'),
        ),
    ]
