# Generated by Django 2.0.6 on 2018-07-04 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20180615_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 10, 33, 22, 624430)),
        ),
    ]
