# Generated by Django 2.0.6 on 2018-07-04 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20180704_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 4, 10, 48, 14, 538509)),
        ),
    ]
