# Generated by Django 2.0.6 on 2018-07-04 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20180704_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 11, 18, 15, 863593)),
        ),
    ]
