# Generated by Django 2.0.6 on 2018-06-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
    ]
